[workspace]
resolver = "2"
exclude = [
    "examples/lambda",
    "examples/webassembly",
    "examples/examples",
    "examples/test-utils",
    "examples/cross_service",
    "tests/telemetry",
    "tests/webassembly",
    "tests/no-default-features"
]
members = [
    "sdk/ec2"
]
